# MCP Server Configuration
# Enterprise middleware and service settings

server:
  name: "TechCorp MCP Server"
  version: "1.0.0"
  host: "localhost"
  port: 8000
  
# Authentication Configuration
authentication:
  enabled: true
  jwt:
    secret_key: "techcorp-mcp-secret"
    algorithm: "HS256"
    access_token_expire_minutes: 30
    
  # User Database (for workshop - use real auth service in production)
  users:
    admin:
      username: "admin"
      password_hash: "hashed_password"
      roles: ["admin", "user"]
      
    user:
      username: "user" 
      password_hash: "hashed_password"
      roles: ["user"]

# Rate Limiting Configuration
rate_limiting:
  enabled: true
  requests_per_minute: 100
  burst_limit: 20
  
# Circuit Breaker Configuration  
circuit_breaker:
  failure_threshold: 5
  recovery_timeout: 60
  half_open_max_calls: 3
  
# Health Check Configuration
health_checks:
  enabled: true
  endpoints:
    health: "/health"
    ready: "/ready"
    metrics: "/metrics"
    
# Audit Logging
audit:
  enabled: true
  log_file: "logs/mcp_server_audit.log"
  log_requests: true
  log_responses: false  # Don't log response data for security
  
# MCP Tools Configuration
tools:
  customer_service:
    - name: "search_knowledge"
      description: "Search the knowledge base"
      parameters:
        query: "string"
        max_results: "integer"
        
    - name: "escalate_conversation"
      description: "Escalate to human agent"
      parameters:
        conversation_id: "string"
        reason: "string"
        
    - name: "get_customer_info"
      description: "Retrieve customer information"
      parameters:
        customer_id: "string"